version: '3.8'

services:
  app:
    build: .
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/cms
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cms
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: